### PR TITLE
Make cimgui a module under a directory dependency

### PR DESCRIPTION
**Pull request by geooot**
- Removes cimgui folder
- Creates `deps/cimgui` dependency which takes c source of cimgui and imgui and makes a static library out of it
- Ran translate-C on `cimgui.h` as a build step so that you don't need to inline it in the main.zig source 
- Changed root build zig to use the new dependency

### CODE REVIEW

**Comment by floooh** [comment]
Thanks! Giving this a whirl now. I'll probably change the commit shas in build.zig.zon to more readable git tag names.

**Comment by floooh** [comment]
Btw, is `ziphfile` a typo or does that have a specific meaning? :)

https://github.com/floooh/sokol-zig-imgui-sample/blob/66d5151f5349ac0e9fa6f0c5480f71d3d7d99288/deps/cimgui/build.zig#L43

**Comment by floooh** [comment]
Really loving the PR, thanks a lot :)

**Comment by geooot** [comment]
> Btw, is `ziphfile` a typo or does that have a specific meaning? :)
> 
> https://github.com/floooh/sokol-zig-imgui-sample/blob/66d5151f5349ac0e9fa6f0c5480f71d3d7d99288/deps/cimgui/build.zig#L43

@floooh Ah that was a copy paste error on my part. The variable represents the path to the header file. Probably "cimgui_h" is a better name.

**Comment by floooh** [comment]
Ok I'll change that. Otherwise everything merged and ready to go.

**Pull request merged**
